language: php
sudo: false
php:
  - 7.0
  - 7.1
  - 7.2
services: redis-server
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
script:
  - vendor/bin/phpunit tests
matrix:
  fast_finish: true
